// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7DlvNcgokJrgDFAusS5h5OgMWfl3mbwE',
    appId: '1:402643615494:web:c46893cb7414458fc22887',
    messagingSenderId: '402643615494',
    projectId: 'sigin-f969c',
    authDomain: 'sigin-f969c.firebaseapp.com',
    storageBucket: 'sigin-f969c.appspot.com',
    measurementId: 'G-VR20QS2WLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMPn0vxFU712pgnvxY5xbLdJ1pf4P5eI',
    appId: '1:402643615494:android:2e8553bf9b1a6d0dc22887',
    messagingSenderId: '402643615494',
    projectId: 'sigin-f969c',
    storageBucket: 'sigin-f969c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZEIPwIEwZ75tn-trsggwOmiGHU3ltfY',
    appId: '1:402643615494:ios:11c824f3d6f79482c22887',
    messagingSenderId: '402643615494',
    projectId: 'sigin-f969c',
    storageBucket: 'sigin-f969c.appspot.com',
    iosBundleId: 'com.example.pi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWZEIPwIEwZ75tn-trsggwOmiGHU3ltfY',
    appId: '1:402643615494:ios:11c824f3d6f79482c22887',
    messagingSenderId: '402643615494',
    projectId: 'sigin-f969c',
    storageBucket: 'sigin-f969c.appspot.com',
    iosBundleId: 'com.example.pi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7DlvNcgokJrgDFAusS5h5OgMWfl3mbwE',
    appId: '1:402643615494:web:5a7f10c6b748de92c22887',
    messagingSenderId: '402643615494',
    projectId: 'sigin-f969c',
    authDomain: 'sigin-f969c.firebaseapp.com',
    storageBucket: 'sigin-f969c.appspot.com',
    measurementId: 'G-MFMKFF0251',
  );
}
